Repository DA-ETSIINF/TryIT, pull requests merged in 2019-02, with the labels that each got.

#74 Merge issue #73
  congress/static/congress/css/home.css
  congress/static/congress/img/2019/2019_hashcode.png
  congress/static/congress/img/2019/partners/2019_bronze_bbva.png
  congress/static/congress/img/2019/partners/2019_bronze_bbva_next.png
  congress/static/congress/img/2019/partners/2019_bronze_paradigma.png
  congress/static/congress/img/2019/partners/2019_bronze_vipera.png
  congress/static/congress/img/2019/partners/2019_oro_deloitte.png
  congress/static/congress/img/2019/partners/2019_oro_gmv.png
  congress/static/congress/img/2019/partners/2019_oro_idom.png
  congress/static/congress/img/2019/partners/2019_oro_thecocktail.png
  congress/static/congress/img/2019/partners/2019_silver_everis.png
  congress/static/congress/img/2019/partners/2019_silver_lineadirecta.jpg
  congress/static/congress/img/2019/partners/2019_silver_mso.jpg
  congress/static/congress/img/2019/partners/2019_silver_neoris.png
  congress/static/congress/img/2019/partners/2019_silver_om.png
  congress/static/congress/img/partners/2018_bronze_aplus.png
  congress/static/congress/img/partners/2018_bronze_atos.png
  congress/static/congress/img/partners/2018_bronze_exevi.png
  congress/static/congress/img/partners/2018_bronze_inspiring_benefits.png
  congress/static/congress/img/partners/2018_oro_accenture.png
  congress/static/congress/img/partners/2018_oro_axa.png
  congress/static/congress/img/partners/2018_silver_babel.png
  congress/templates/congress/home.html
  congress/templates/congress/workshops.html
Labels: enhancement, priority/P1

#72 Create LICENSE
  LICENSE
Labels: enhancement, priority/P1

#95 Merge README (Issue 15)
  README.md
  requirements.txt
Labels: enhancement

#115 fixed issue 113
  congress/static/congress/angular/app.js
  events/templates/events/escape-room.html
Labels: bug, priority/P1
